name: Deploy to linode

on:
  push:
    branches:
      - main

jobs: 
  deploy: 
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
        chmod 600 ~/.ssh/id_ed25519
        ssh-keyscan 45.79.123.206 >> ~/.ssh/known_hosts
    
    - name: Deploy over SSH
      run: |
        ssh -i ~/.ssh/id_ed25519 ajay@45.79.123.206 << 'EOF'
          cd ~/myapp
          git pull origin main
          npm install
          pm2 restart myapp
        EOF